export const ACTION_TYPE = {
	SET_TODOS: 'SET_TODOS',
	ADD_TODO: 'ADD_TODO',
	REMOVE_TODO: 'REMOVE_TODO',
	UPDATE_TODO: 'UPDATE_TODO',
	EDIT_TODO: 'EDIT_TODO',
	FINISH_EDIT_TODO: 'FINISH_EDIT_TODO',
	LOADING_START: 'LOADING_START',
	LOADING_END: 'LOADING_END',
	SET_SEARCH_INPUT: 'SET_SEARCH_INPUT',
	SET_SORTING: 'SET_SORTING',
}
